<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class Shahrestanseeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('shahrestans')->insert([
            
            ['id'=>'1', 'ostan_id'=>'1', 'shahrestan'=>' آذرشهر',],
            ['id'=>'2', 'ostan_id'=>'1', 'shahrestan'=>' اسکو',],
            ['id'=>'3', 'ostan_id'=>'1', 'shahrestan'=>' اهر',],
            ['id'=>'4', 'ostan_id'=>'1', 'shahrestan'=>' بستان آباد', ],
            ['id'=>'5', 'ostan_id'=>'1', 'shahrestan'=>' بناب', ],
            ['id'=>'6', 'ostan_id'=>'1', 'shahrestan'=>' تبریز', ],
            ['id'=>'7', 'ostan_id'=>'1', 'shahrestan'=>' جلفا', ],
            ['id'=>'8', 'ostan_id'=>'1', 'shahrestan'=>' چار اویماق',],
            ['id'=>'9', 'ostan_id'=>'1', 'shahrestan'=>' سراب', ],
            ['id'=>'10','ostan_id'=> '1','shahrestan'=> ' شبستر', ],
            ['id'=>'11','ostan_id'=> '1','shahrestan'=> ' عجبشیر', ],
            ['id'=>'12','ostan_id'=> '1','shahrestan'=> ' کلیبر', ],
            ['id'=>'13','ostan_id'=> '1','shahrestan'=> ' مراغه', ],
            ['id'=>'14','ostan_id'=> '1','shahrestan'=> ' مرند', ],
            ['id'=>'15','ostan_id'=> '1','shahrestan'=> ' ملکان', ],
            ['id'=>'16','ostan_id'=> '1','shahrestan'=> ' میانه', ],
            ['id'=>'17','ostan_id'=> '1','shahrestan'=> ' ورزقان', ],
            ['id'=>'18','ostan_id'=> '1','shahrestan'=> ' هریس', ],
            ['id'=>'19','ostan_id'=> '1','shahrestan'=> 'هشترود', ],
            ['id'=>'20','ostan_id'=> '2','shahrestan'=> ' ارومیه', ],
            ['id'=>'21','ostan_id'=> '2','shahrestan'=> ' اشنویه', ],
            ['id'=>'22','ostan_id'=> '2','shahrestan'=> ' بوکان', ],
            ['id'=>'23','ostan_id'=> '2','shahrestan'=> ' پیرانشهر',],
            ['id'=>'24','ostan_id'=> '2','shahrestan'=> ' تکاب', ],
            ['id'=>'25','ostan_id'=> '2','shahrestan'=> ' چالدران', ],
            ['id'=>'26','ostan_id'=> '2','shahrestan'=> ' خوی', ],
            ['id'=>'27','ostan_id'=> '2','shahrestan'=> ' سردشت', ],
            ['id'=>'28','ostan_id'=> '2','shahrestan'=> ' سلماس', ],
            ['id'=>'29','ostan_id'=> '2','shahrestan'=> ' شاهین دژ', ],
            ['id'=>'30','ostan_id'=> '2','shahrestan'=> ' ماکو', ],
            ['id'=>'31','ostan_id'=> '2','shahrestan'=> ' مهاباد', ],
            ['id'=>'32','ostan_id'=> '2','shahrestan'=> ' میاندوآب', ],
            ['id'=>'33','ostan_id'=> '2','shahrestan'=> ' نقده', ],
            ['id'=>'34','ostan_id'=> '3','shahrestan'=> ' اردبیل', ],
            ['id'=>'35','ostan_id'=> '3','shahrestan'=> ' بیله سوار', ],
            ['id'=>'36','ostan_id'=> '3','shahrestan'=> ' پارس آباد', ],
            ['id'=>'37','ostan_id'=> '3','shahrestan'=> ' خلخال', ],
            ['id'=>'38','ostan_id'=> '3','shahrestan'=> ' کوثر', ],
            ['id'=>'39','ostan_id'=> '3','shahrestan'=> ' گرمی', ],
            ['id'=>'40','ostan_id'=> '3','shahrestan'=> ' مشگین', ],
            ['id'=>'41','ostan_id'=> '3','shahrestan'=> ' نمین', ],
            ['id'=>'42','ostan_id'=> '3','shahrestan'=> ' نیر', ],
            ['id'=>'43','ostan_id'=> '4','shahrestan'=> ' آران و بیدگل',],
            ['id'=>'44','ostan_id'=> '4','shahrestan'=> ' اردستان',],
            ['id'=>'45','ostan_id'=> '4','shahrestan'=> ' اصفهان', ],
            ['id'=>'46','ostan_id'=> '4','shahrestan'=> ' برخوار و میم',],
            ['id'=>'47','ostan_id'=> '4','shahrestan'=> ' تیران و کرون',],
            ['id'=>'48','ostan_id'=> '4','shahrestan'=> ' چادگان',],
            ['id'=>'49','ostan_id'=> '4','shahrestan'=> ' خمینی شهر', ],
            ['id'=>'50','ostan_id'=> '4','shahrestan'=> ' خوانسار', ],
            ['id'=>'51','ostan_id'=> '4','shahrestan'=> ' سمیرم', ],
            ['id'=>'52','ostan_id'=> '4','shahrestan'=> ' شاهین شهر و ', ],
            ['id'=>'53','ostan_id'=> '4','shahrestan'=> ' شهر رضا', ],
            ['id'=>'54','ostan_id'=> '4','shahrestan'=> 'دهاقان', ],
            ['id'=>'55','ostan_id'=> '4','shahrestan'=> ' فریدن', ],
            ['id'=>'56','ostan_id'=> '4','shahrestan'=> ' فریدون شهر',],
            ['id'=>'57','ostan_id'=> '4','shahrestan'=> ' فلاورجان', ],
            ['id'=>'58','ostan_id'=> '4','shahrestan'=> ' کاشان', ],
            ['id'=>'59','ostan_id'=> '4','shahrestan'=> ' گلپایگان',],
            ['id'=>'60','ostan_id'=> '4','shahrestan'=> ' لنجان',],
            ['id'=>'61','ostan_id'=> '4','shahrestan'=> ' مبارکه',],
            ['id'=>'62','ostan_id'=> '4','shahrestan'=> ' نائین', ],
            ['id'=>'63','ostan_id'=> '4','shahrestan'=> ' نجف آباد', ],
            ['id'=>'64','ostan_id'=> '4','shahrestan'=> ' نطنز', ],
            ['id'=>'65','ostan_id'=> '5','shahrestan'=> ' ساوجبلاق', ],
            ['id'=>'66','ostan_id'=> '5','shahrestan'=> ' کرج', ],
            ['id'=>'67','ostan_id'=> '5','shahrestan'=> ' نظرآباد', ],
            ['id'=>'68','ostan_id'=> '5','shahrestan'=> 'طالقان', ],
            ['id'=>'69','ostan_id'=> '6','shahrestan'=> ' آبدانان', ],
            ['id'=>'70','ostan_id'=> '6','shahrestan'=> ' ایلام', ],
            ['id'=>'71','ostan_id'=> '6','shahrestan'=> ' ایوان', ],
            ['id'=>'72','ostan_id'=> '6','shahrestan'=> ' دره شهر',],
            ['id'=>'73','ostan_id'=> '6','shahrestan'=> ' دهلران', ],
            ['id'=>'74','ostan_id'=> '6','shahrestan'=> ' شیران و چردا',],
            ['id'=>'75','ostan_id'=> '6','shahrestan'=> ' مهران', ],
            ['id'=>'76','ostan_id'=> '7','shahrestan'=> ' بوشهر', ],
            ['id'=>'77','ostan_id'=> '7','shahrestan'=> ' تنگستان', ],
            ['id'=>'78','ostan_id'=> '7','shahrestan'=> ' جم', ],
            ['id'=>'79','ostan_id'=> '7','shahrestan'=> ' دشتستان', ],
            ['id'=>'80','ostan_id'=> '7','shahrestan'=> ' دشتی', ],
            ['id'=>'81','ostan_id'=> '7','shahrestan'=> ' دیر', ],
            ['id'=>'82','ostan_id'=> '7','shahrestan'=> ' دیلم', ],
            ['id'=>'83','ostan_id'=> '7','shahrestan'=> ' کنگان', ],
            ['id'=>'84','ostan_id'=> '7','shahrestan'=> ' گناوه', ],
            ['id'=>'85','ostan_id'=> '8','shahrestan'=> ' اسلام شهر', ],
            ['id'=>'86','ostan_id'=> '8','shahrestan'=> ' پاکدشت', ],
            ['id'=>'87','ostan_id'=> '8','shahrestan'=> ' تهران', ],
            ['id'=>'88','ostan_id'=> '8','shahrestan'=> ' دماوند', ],
            ['id'=>'89','ostan_id'=> '8','shahrestan'=> ' رباط کریم', ],
            ['id'=>'90','ostan_id'=> '8','shahrestan'=> ' ری', ],
            ['id'=>'91','ostan_id'=> '8','shahrestan'=> ' شمیرانات',],
            ['id'=>'92','ostan_id'=> '8','shahrestan'=> ' شهریار', ],
            ['id'=>'93','ostan_id'=> '8','shahrestan'=> ' فیروزکوه',],
            ['id'=>'94','ostan_id'=> '8','shahrestan'=> ' ورامین', ],
            ['id'=>'95','ostan_id'=> '9','shahrestan'=> ' اردل', ],
            ['id'=>'96','ostan_id'=> '9','shahrestan'=> ' بروجن', ],
            ['id'=>'97','ostan_id'=> '9','shahrestan'=> ' شهرکرد',],
            ['id'=>'98','ostan_id'=> '9','shahrestan'=> ' فارسان',],
            ['id'=>'99','ostan_id'=> '9','shahrestan'=> ' کوهرنگ',],
            ['id'=>'100','ostan_id'=> '9','shahrestan'=> ' لردگان',],
            ['id'=>'101','ostan_id'=> '10','shahrestan'=> 'بیرجند',],
            ['id'=>'102','ostan_id'=> '10','shahrestan'=> 'درمیان',],
            ['id'=>'103','ostan_id'=> '10','shahrestan'=> 'سرایان',],
            ['id'=>'104','ostan_id'=> '10','shahrestan'=> 'سر بیشه',],
            ['id'=>'105','ostan_id'=> '10','shahrestan'=> 'فردوس', ],
            ['id'=>'106','ostan_id'=> '10','shahrestan'=>'قائن', ],
            ['id'=>'107','ostan_id'=> '10','shahrestan'=> 'نهبندان',],
            ['id'=>'108','ostan_id'=> '11','shahrestan'=> 'برد سکن',],
            ['id'=>'109','ostan_id'=> '11','shahrestan'=> 'بجستان',],
            ['id'=>'110','ostan_id'=> '11','shahrestan'=> 'تایباد',],
            ['id'=>'111','ostan_id'=> '11','shahrestan'=> 'تحت جلگه',],
            ['id'=>'112','ostan_id'=> '11','shahrestan'=> 'تربت جام',],
            ['id'=>'113','ostan_id'=> '11','shahrestan'=> 'تربت حیدریه',],
            ['id'=>'114','ostan_id'=> '11','shahrestan'=> 'چناران',],
            ['id'=>'115','ostan_id'=> '11','shahrestan'=>' جغتای', ],
            ['id'=>'116','ostan_id'=> '11','shahrestan'=> 'جوین',],
            ['id'=>'117','ostan_id'=> '11','shahrestan'=> 'خلیل آباد', ],
            ['id'=>'118','ostan_id'=> '11','shahrestan'=> 'خواف', ],
            ['id'=>'119','ostan_id'=> '11','shahrestan'=> 'درگز', ],
            ['id'=>'120','ostan_id'=> '11','shahrestan'=> 'رشتخوار',],
            ['id'=>'121','ostan_id'=> '11','shahrestan'=> 'زاوه', ],
            ['id'=>'122','ostan_id'=> '11','shahrestan'=> 'سبزوار', ],
            ['id'=>'123','ostan_id'=> '11','shahrestan'=> 'سرخس', ],
            ['id'=>'124','ostan_id'=> '11','shahrestan'=> 'فریمان', ],
            ['id'=>'125','ostan_id'=> '11','shahrestan'=> 'قوچان', ],
            ['id'=>'126','ostan_id'=> '11','shahrestan'=>'طرقبه شاندیز',],
            ['id'=>'127','ostan_id'=> '11','shahrestan'=> 'کاشمر',],
            ['id'=>'128','ostan_id'=> '11','shahrestan'=> 'کلات', ],
            ['id'=>'129','ostan_id'=> '11','shahrestan'=> 'گناباد',],
            ['id'=>'130','ostan_id'=> '11','shahrestan'=> 'مشهد', ],
            ['id'=>'131','ostan_id'=> '11','shahrestan'=>'مه ولات',],
            ['id'=>'132','ostan_id'=> '11','shahrestan'=> 'نیشابور', ],
            ['id'=>'133','ostan_id'=> '12','shahrestan'=> 'اسفراین', ],
            ['id'=>'134','ostan_id'=> '12','shahrestan'=> 'بجنورد', ],
            ['id'=>'135','ostan_id'=> '12','shahrestan'=> 'جاجرم', ],
            ['id'=>'136','ostan_id'=> '12','shahrestan'=> 'شیروان',],
            ['id'=>'137','ostan_id'=> '12','shahrestan'=> 'فاروج', ],
            ['id'=>'138','ostan_id'=> '12','shahrestan'=> 'مانه و سملقا',],
            ['id'=>'139','ostan_id'=> '13','shahrestan'=> 'آبادان',],
            ['id'=>'140','ostan_id'=> '13','shahrestan'=> 'امیدیه', ],
            ['id'=>'141','ostan_id'=> '13','shahrestan'=> 'اندیمشک',],
            ['id'=>'142','ostan_id'=> '13','shahrestan'=>'اهواز',],
            ['id'=>'143','ostan_id'=> '13','shahrestan'=> 'ایذه', ],
            ['id'=>'144','ostan_id'=> '13','shahrestan'=> 'باغ ملک',],
            ['id'=>'145','ostan_id'=> '13','shahrestan'=> 'بندرماهشهر',],
            ['id'=>'146','ostan_id'=> '13','shahrestan'=>'بهبهان',],
            ['id'=>'147','ostan_id'=> '13','shahrestan'=> 'خرمشهر' ,],
            ['id'=>'148','ostan_id'=> '13','shahrestan'=> 'دزفول',],
            ['id'=>'149','ostan_id'=> '13','shahrestan'=>' دشت آزادگان',],
            ['id'=>'150','ostan_id'=> '13','shahrestan'=> 'رامشیر',],
            ['id'=>'151','ostan_id'=> '13','shahrestan'=> 'رامهرمز',],
            ['id'=>'152','ostan_id'=> '13','shahrestan'=> 'شادگان', ],
            ['id'=>'153','ostan_id'=> '13','shahrestan'=> 'شوش',],
            ['id'=>'154','ostan_id'=> '13','shahrestan'=> 'شوشتر'],
            ['id'=>'155','ostan_id'=> '13','shahrestan'=> 'گتوند'],
            ['id'=>'156','ostan_id'=> '13','shahrestan'=> 'لالی'],
            ['id'=>'157','ostan_id'=> '13','shahrestan'=> 'مسجد سلیمان'],
            ['id'=>'158','ostan_id'=> '13','shahrestan'=> 'هندیجان',],
            ['id'=>'159','ostan_id'=> '14','shahrestan'=> 'ابهر',],
            ['id'=>'160','ostan_id'=> '14','shahrestan'=> 'ایجرود',],
            ['id'=>'161','ostan_id'=> '14','shahrestan'=> 'خدابنده'],
            ['id'=>'162','ostan_id'=> '14','shahrestan'=> 'خرمدره',],
            ['id'=>'163','ostan_id'=> '14','shahrestan'=> 'زنجان',],
            ['id'=>'164','ostan_id'=> '14','shahrestan'=> 'طارم',],
            ['id'=>'165','ostan_id'=> '14','shahrestan'=> 'ماه نشان'],
            ['id'=>'166','ostan_id'=> '15','shahrestan'=> 'دامغان',],
            ['id'=>'167','ostan_id'=> '15','shahrestan'=> 'سمنان'],
            ['id'=>'168','ostan_id'=> '15','shahrestan'=> 'شاهرود'],
            ['id'=>'169','ostan_id'=> '15','shahrestan'=> 'گرمسار'],
            ['id'=>'170','ostan_id'=> '15','shahrestan'=> 'مهدی شهر'],
            ['id'=>'171','ostan_id'=> '16','shahrestan'=> 'ایرانشهر'],
            ['id'=>'172','ostan_id'=> '16','shahrestan'=> 'چابهار'],
            ['id'=>'173','ostan_id'=> '16','shahrestan'=>' خاش'],
            ['id'=>'174','ostan_id'=> '16','shahrestan'=> 'دلگان',],
            ['id'=>'175','ostan_id'=> '16','shahrestan'=> 'زابل',],
            ['id'=>'176','ostan_id'=> '16','shahrestan'=> 'زاهدان',],
            ['id'=>'177','ostan_id'=> '16','shahrestan'=>' زهک'],
            ['id'=>'178','ostan_id'=> '16','shahrestan'=> 'سراوان'],
            ['id'=>'179','ostan_id'=> '16','shahrestan'=> 'سرباز',],
            ['id'=>'180','ostan_id'=> '16','shahrestan'=> 'کنارک'],
            ['id'=>'181','ostan_id'=> '16','shahrestan'=> 'نیکشهر',],
            ['id'=>'182','ostan_id'=> '17','shahrestan'=> 'آباده'],
            ['id'=>'183','ostan_id'=> '17','shahrestan'=> 'ارسنجان'],
            ['id'=>'184','ostan_id'=> '17','shahrestan'=> 'استهبان',],
            ['id'=>'185','ostan_id'=> '17','shahrestan'=> 'اقلید',],
            ['id'=>'186','ostan_id'=> '17','shahrestan'=>' بوانات',],
            ['id'=>'187','ostan_id'=> '17','shahrestan'=> 'پاسارگاد',],
            ['id'=>'188','ostan_id'=> '17','shahrestan'=> 'جهرم'],
            ['id'=>'189','ostan_id'=> '17','shahrestan'=> 'خرم بید'],
            ['id'=>'190','ostan_id'=> '17','shahrestan'=> 'خنج'],
            ['id'=>'191','ostan_id'=> '17','shahrestan'=> ' داراب'],
            ['id'=>'192','ostan_id'=> '17','shahrestan'=> ' زرین دشت'],
            ['id'=>'193','ostan_id'=> '17','shahrestan'=> 'سپیدان'],
            ['id'=>'194','ostan_id'=> '17','shahrestan'=> 'شیراز'],
            ['id'=>'195','ostan_id'=> '17','shahrestan'=> 'فراشبند'],
            ['id'=>'196','ostan_id'=> '17','shahrestan'=> 'فسا',],
            ['id'=>'197','ostan_id'=> '17','shahrestan'=> 'فیروزآباد',],
            ['id'=>'198','ostan_id'=> '17','shahrestan'=> 'قیر و کارزین'],
            ['id'=>'199','ostan_id'=> '17','shahrestan'=> 'کازرون'],
            ['id'=>'200','ostan_id'=> '17','shahrestan'=> 'لارستان'],
            ['id'=>'201','ostan_id'=> '17','shahrestan'=> 'لامرد'],
            ['id'=>'202','ostan_id'=> '17','shahrestan'=> 'مرودشت',],
            ['id'=>'203','ostan_id'=> '17','shahrestan'=> 'ممسنی'],
            ['id'=>'204','ostan_id'=> '17','shahrestan'=> 'گمهر',],
            ['id'=>'206','ostan_id'=> '18','shahrestan'=> 'آبیک',],
            ['id'=>'207','ostan_id'=> '18','shahrestan'=> 'البرز',],
            ['id'=>'208','ostan_id'=> '18','shahrestan'=> 'بوئین زهرا'],
            ['id'=>'209','ostan_id'=> '18','shahrestan'=> 'تاکستان',],
            ['id'=>'210','ostan_id'=> '18','shahrestan'=> 'قزوین',],
            ['id'=>'211','ostan_id'=> '19','shahrestan'=> 'قم',],
            ['id'=>'212','ostan_id'=> '20','shahrestan'=> 'بانه',],
            ['id'=>'213','ostan_id'=> '20','shahrestan'=> 'بیجار',],
            ['id'=>'214','ostan_id'=> '20','shahrestan'=> 'دیواندره',],
            ['id'=>'215','ostan_id'=> '20','shahrestan'=> 'سروآباد',],
            ['id'=>'216','ostan_id'=> '20','shahrestan'=> 'سقز',],
            ['id'=>'217','ostan_id'=> '20','shahrestan'=> ' سنندج',],
            ['id'=>'218','ostan_id'=> '20','shahrestan'=> 'قروه'],
            ['id'=>'219','ostan_id'=> '20','shahrestan'=> 'کامیاران'],
            ['id'=>'220','ostan_id'=> '20','shahrestan'=> 'مریوان',],
            ['id'=>'221','ostan_id'=> '21','shahrestan'=> 'بافت'],
            ['id'=>'222','ostan_id'=> '21','shahrestan'=> 'بردسیر',],
            ['id'=>'223','ostan_id'=> '21','shahrestan'=> 'بم',],
            ['id'=>'224','ostan_id'=> '21','shahrestan'=> 'جیرفت'],
            ['id'=>'225','ostan_id'=> '21','shahrestan'=> 'راور'],
            ['id'=>'226','ostan_id'=> '21','shahrestan'=> 'رفسنجان'],
            ['id'=>'227','ostan_id'=> '21','shahrestan'=> 'رودبار جنوب'],
            ['id'=>'228','ostan_id'=> '21','shahrestan'=> 'زرند'],
            ['id'=>'229','ostan_id'=> '21','shahrestan'=> 'سیرجان'],
            ['id'=>'230','ostan_id'=> '21','shahrestan'=> 'شهر بابک'],
            ['id'=>'231','ostan_id'=> '21','shahrestan'=> 'عنبرآباد'],
            ['id'=>'232','ostan_id'=> '21','shahrestan'=> 'قلعه گنج'],
            ['id'=>'233','ostan_id'=> '21','shahrestan'=> 'کرمان',],
            ['id'=>'234','ostan_id'=> '21','shahrestan'=> 'کوهبنان'],
            ['id'=>'235','ostan_id'=> '21','shahrestan'=> 'کهنوج'],
            ['id'=>'236','ostan_id'=> '21','shahrestan'=> 'منوجان',],
            ['id'=>'237','ostan_id'=> '22','shahrestan'=> 'اسلام آباد غ'],
            ['id'=>'238','ostan_id'=> '22','shahrestan'=> 'پاوه'],
            ['id'=>'239','ostan_id'=> '22','shahrestan'=> 'ثلاث باباجان'],
            ['id'=>'240','ostan_id'=> '22','shahrestan'=> 'جوانرود'],
            ['id'=>'241','ostan_id'=> '22','shahrestan'=> 'دالاهو'],
            ['id'=>'242','ostan_id'=> '22','shahrestan'=> 'روانسر'],
            ['id'=>'243','ostan_id'=> '22','shahrestan'=> 'سرپل ذهاب'],
            ['id'=>'244','ostan_id'=> '22','shahrestan'=> 'سنقر'],
            ['id'=>'245','ostan_id'=> '22','shahrestan'=> 'صحنه'],
            ['id'=>'246','ostan_id'=> '22','shahrestan'=> 'قصر شیرین',],
            ['id'=>'247','ostan_id'=> '22','shahrestan'=> 'کرمانشاه',],
            ['id'=>'248','ostan_id'=> '22','shahrestan'=> 'کنگاور'],
            ['id'=>'249','ostan_id'=> '22','shahrestan'=> 'گیلان غرب',],
            ['id'=>'250','ostan_id'=> '22','shahrestan'=> 'هرسین'],
            ['id'=>'251','ostan_id'=> '23','shahrestan'=> 'بویر احمد'],
            ['id'=>'252','ostan_id'=> '23','shahrestan'=> 'بهمئی'],
            ['id'=>'253','ostan_id'=> '23','shahrestan'=> 'دنا',],
            ['id'=>'254','ostan_id'=> '23','shahrestan'=> 'کهگیلویه'],
            ['id'=>'255','ostan_id'=> '23','shahrestan'=> 'گچساران'],
            ['id'=>'256','ostan_id'=> '24','shahrestan'=> 'آزادشهر'],
            ['id'=>'257','ostan_id'=> '24','shahrestan'=> 'آق قلا',],
            ['id'=>'258','ostan_id'=> '24','shahrestan'=> 'بندر گز'],
            ['id'=>'259','ostan_id'=> '24','shahrestan'=> 'بندر ترکمن'],
            ['id'=>'260','ostan_id'=> '24','shahrestan'=> 'رامیان',],
            ['id'=>'261','ostan_id'=> '24','shahrestan'=> 'علی آباد'],
            ['id'=>'262','ostan_id'=> '24','shahrestan'=> 'کرد کوی'],
            ['id'=>'263','ostan_id'=> '24','shahrestan'=> 'کلاله',],
            ['id'=>'264','ostan_id'=> '24','shahrestan'=> 'گرگان',],
            ['id'=>'265','ostan_id'=> '24','shahrestan'=> 'گنبد کاووس'],
            ['id'=>'266','ostan_id'=> '24','shahrestan'=> 'مینو دشت',],
            ['id'=>'267','ostan_id'=> '25','shahrestan'=> 'آستارا'],
            ['id'=>'268','ostan_id'=> '25','shahrestan'=> 'آستانه اشرفی'],
            ['id'=>'269','ostan_id'=> '25','shahrestan'=> 'املش'],
            ['id'=>'270','ostan_id'=> '25','shahrestan'=>'بندر انزلی'],
            ['id'=>'271','ostan_id'=> '25','shahrestan'=>' رشت'],
            ['id'=>'272','ostan_id'=> '25','shahrestan'=> 'رضوانشهر'],
            ['id'=>'273','ostan_id'=> '25','shahrestan'=> 'رودبار'],
            ['id'=>'274','ostan_id'=> '25','shahrestan'=> 'رودسر'],
            ['id'=>'275','ostan_id'=> '25','shahrestan'=> 'سیاهکل'],
            ['id'=>'276','ostan_id'=> '25','shahrestan'=> 'شفت',],
            ['id'=>'277','ostan_id'=> '25','shahrestan'=> 'صومعه سرا'],
            ['id'=>'278','ostan_id'=> '25','shahrestan'=> 'طوالش'],
            ['id'=>'279','ostan_id'=> '25','shahrestan'=>'فومن'],
            ['id'=>'280','ostan_id'=> '25','shahrestan'=> 'لاهیجان'],
            ['id'=>'281','ostan_id'=> '25','shahrestan'=> 'لنگرود'],
            ['id'=>'282','ostan_id'=> '25','shahrestan'=> 'ماسال',],
            ['id'=>'283','ostan_id'=> '26','shahrestan'=> 'ازنا',],
            ['id'=>'284','ostan_id'=> '26','shahrestan'=> 'الیگودرز'],
            ['id'=>'285','ostan_id'=> '26','shahrestan'=> 'بروجرد'],
            ['id'=>'286','ostan_id'=> '26','shahrestan'=> 'پلدختر',],
            ['id'=>'287','ostan_id'=> '26','shahrestan'=> 'خرم آباد'],
            ['id'=>'288','ostan_id'=> '26','shahrestan'=> 'دورود'],
            ['id'=>'289','ostan_id'=> '17','shahrestan'=> 'لامرد',],
            ['id'=>'290','ostan_id'=> '17','shahrestan'=>' مرودشت',],
            ['id'=>'291','ostan_id'=> '17','shahrestan'=> 'ممسنی',],
            ['id'=>'292','ostan_id'=> '17','shahrestan'=> 'مهر',],
            ['id'=>'293','ostan_id'=> '17','shahrestan'=> 'نی ریز'],
            ['id'=>'294','ostan_id'=> '18','shahrestan'=> 'آبیک',],
            ['id'=>'295','ostan_id'=> '18','shahrestan'=> 'البرز',],
            ['id'=>'296','ostan_id'=> '18','shahrestan'=> 'بوئین زهرا'],
            ['id'=>'297','ostan_id'=> '18','shahrestan'=> 'تاکستان'],
            ['id'=>'298','ostan_id'=> '18','shahrestan'=> 'قزوین'],
            ['id'=>'299','ostan_id'=> '19','shahrestan'=> 'قم'],
            ['id'=>'300','ostan_id'=> '20','shahrestan'=> 'بانه',],
            ['id'=>'301','ostan_id'=> '20','shahrestan'=> 'بیجار'],
            ['id'=>'302','ostan_id'=> '20','shahrestan'=> 'دیواندره',],
            ['id'=>'303','ostan_id'=> '20','shahrestan'=> 'سروآباد'],
            ['id'=>'304','ostan_id'=> '20','shahrestan'=> 'سقز',],
            ['id'=>'305','ostan_id'=> '20','shahrestan'=> 'سنندج',],
            ['id'=>'306','ostan_id'=> '20','shahrestan'=> 'قروه'],
            ['id'=>'307','ostan_id'=> '20','shahrestan'=> 'کامیاران'],
            ['id'=>'308','ostan_id'=> '20','shahrestan'=> 'مریوان'],
            ['id'=>'309','ostan_id'=> '21','shahrestan'=> 'بافت',],
            ['id'=>'310','ostan_id'=> '21','shahrestan'=> 'بردسیر',],
            ['id'=>'311','ostan_id'=> '21','shahrestan'=> 'بم'],
            ['id'=>'312','ostan_id'=> '21','shahrestan'=> 'جیرفت',],
            ['id'=>'313','ostan_id'=> '21','shahrestan'=> 'راور',],
            ['id'=>'314','ostan_id'=> '21','shahrestan'=> 'رفسنجان',],
            ['id'=>'315','ostan_id'=> '21','shahrestan'=>' رودبار جنوب'],
            ['id'=>'316','ostan_id'=> '21','shahrestan'=> 'زرند'],
            ['id'=>'317','ostan_id'=> '21','shahrestan'=> 'سیرجان'],
            ['id'=>'318','ostan_id'=> '21','shahrestan'=>'شهر بابک'],
            ['id'=>'319','ostan_id'=> '21','shahrestan'=> 'عنبرآباد',],
            ['id'=>'320','ostan_id'=> '21','shahrestan'=> 'قلعه گنج'],
            ['id'=>'321','ostan_id'=> '21','shahrestan'=> 'کرمان'],
            ['id'=>'322','ostan_id'=> '21','shahrestan'=> 'کوهبنان'],
            ['id'=>'323','ostan_id'=> '21','shahrestan'=> 'کهنوج'],
            ['id'=>'324','ostan_id'=> '21','shahrestan'=> 'منوجان'],
            ['id'=>'325','ostan_id'=> '22','shahrestan'=> 'اسلام آباد غ'],
            ['id'=>'326','ostan_id'=> '22','shahrestan'=> 'پاوه'],
            ['id'=>'327','ostan_id'=> '22','shahrestan'=> 'ثلاث باباجان'],
            ['id'=>'328','ostan_id'=> '22','shahrestan'=> 'جوانرود'],
            ['id'=>'329','ostan_id'=> '22','shahrestan'=> 'دالاهو'],
            ['id'=>'330','ostan_id'=> '22','shahrestan'=> 'روانسر'],
            ['id'=>'332','ostan_id'=> '22','shahrestan'=> 'سنقر',],
            ['id'=>'333','ostan_id'=> '22','shahrestan'=> 'صحنه',],
            ['id'=>'334','ostan_id'=> '22','shahrestan'=> 'قصر شیرین',],
            ['id'=>'335','ostan_id'=> '22','shahrestan'=> 'کرمانشاه'],
            ['id'=>'336','ostan_id'=> '22','shahrestan'=> 'کنگاور'],
            ['id'=>'337','ostan_id'=> '22','shahrestan'=> 'گیلان غرب'],
            ['id'=>'338','ostan_id'=> '22','shahrestan'=> 'هرسین'],
            ['id'=>'339','ostan_id'=> '23','shahrestan'=> 'بویر احمد'],
            ['id'=>'341','ostan_id'=> '23','shahrestan'=> 'دنا'],
            ['id'=>'343','ostan_id'=> '23','shahrestan'=> 'گچساران'],
            ['id'=>'344','ostan_id'=> '24','shahrestan'=> 'آزادشهر'],
            ['id'=>'345','ostan_id'=> '24','shahrestan'=> 'آق قلا'],
            ['id'=>'346','ostan_id'=> '24','shahrestan'=> 'بندر گز'],
            ['id'=>'347','ostan_id'=> '24','shahrestan'=> 'بندر ترکمن'],
            ['id'=>'348','ostan_id'=> '24','shahrestan'=> 'رامیان'],
            ['id'=>'349','ostan_id'=> '24','shahrestan'=> 'علی آباد',],
            ['id'=>'350','ostan_id'=> '24','shahrestan'=> 'کرد کوی'],
            ['id'=>'351','ostan_id'=> '24','shahrestan'=> 'کلاله'],
            ['id'=>'352','ostan_id'=> '24','shahrestan'=> 'گرگان',],
            ['id'=>'353','ostan_id'=> '24','shahrestan'=> 'گنبد کاووس'],
            ['id'=>'354','ostan_id'=> '24','shahrestan'=>' مینو دشت'],
            ['id'=>'355','ostan_id'=> '25','shahrestan'=> 'آستارا'],
            ['id'=>'356','ostan_id'=> '25','shahrestan'=>' آستانه اشرفی'],
            ['id'=>'357','ostan_id'=> '25','shahrestan'=> 'املش'],
            ['id'=>'358','ostan_id'=>'25','shahrestan'=>'بندر انزلی',],
            ['id'=>'359','ostan_id'=>'25','shahrestan'=>'رشت',],
            ['id'=>'360','ostan_id'=>'25','shahrestan'=>'رضوانشهر',],
            ['id'=>'361','ostan_id'=>'25','shahrestan'=>'رودبار',],
            ['id'=>'362','ostan_id'=>'25','shahrestan'=>'رودسر',],
            ['id'=>'363','ostan_id'=>'25','shahrestan'=>'سیاهکل',],
            ['id'=>'364','ostan_id'=>'25','shahrestan'=>'شفت',],
            ['id'=>'365','ostan_id'=>'25','shahrestan'=>'صومعه سرا',],
            ['id'=>'366','ostan_id'=>'25','shahrestan'=>'طوالش',],
            ['id'=>'367','ostan_id'=>'25','shahrestan'=>'فومن',],
            ['id'=>'368','ostan_id'=>'25','shahrestan'=>'لاهیجان',],
            ['id'=>'369','ostan_id'=>'25','shahrestan'=>'لنگرود',],
            ['id'=>'370','ostan_id'=>'25','shahrestan'=>'ماسال',],
            ['id'=>'371','ostan_id'=>'26','shahrestan'=>'ازنا',],
            ['id'=>'372','ostan_id'=>'26','shahrestan'=>'الیگودرز',],
            ['id'=>'373','ostan_id'=>'26','shahrestan'=>'بروجرد',],
            ['id'=>'374','ostan_id'=>'26','shahrestan'=>'پلدختر',],
            ['id'=>'375','ostan_id'=>'26','shahrestan'=>'خرم آباد',],
            ['id'=>'376','ostan_id'=>'26','shahrestan'=>'دورود',],
            ['id'=>'377','ostan_id'=>'26','shahrestan'=>'دلفان',],
            ['id'=>'378','ostan_id'=>'26','shahrestan'=>'سلسله',],
            ['id'=>'379','ostan_id'=>'26','shahrestan'=>'کوهدشت',],
            ['id'=>'380','ostan_id'=>'26','shahrestan'=>'الشتر',],
            ['id'=>'381','ostan_id'=>'26','shahrestan'=>'نورآباد',],
            ['id'=>'382','ostan_id'=>'27','shahrestan'=>'آمل',],
            ['id'=>'383','ostan_id'=>'27','shahrestan'=>'بابل',],
            ['id'=>'384','ostan_id'=>'27','shahrestan'=>'بابلسر',],
            ['id'=>'385','ostan_id'=>'27','shahrestan'=>'بهشهر',],
            ['id'=>'386','ostan_id'=>'27','shahrestan'=>'تنکابن',],
            ['id'=>'387','ostan_id'=>'27','shahrestan'=>'جویبار',],
            ['id'=>'388','ostan_id'=>'27','shahrestan'=>'چالوس',],
            ['id'=>'389','ostan_id'=>'27','shahrestan'=>'رامسر',],
            ['id'=>'390','ostan_id'=>'27','shahrestan'=>'ساری',],
            ['id'=>'391','ostan_id'=>'27','shahrestan'=>'سوادکوه',],
            ['id'=>'392','ostan_id'=>'27','shahrestan'=>'قائم شهر',],
            ['id'=>'393','ostan_id'=>'27','shahrestan'=>'گلوگاه',],
            ['id'=>'394','ostan_id'=>'27','shahrestan'=>'محمود آباد',],
            ['id'=>'395','ostan_id'=>'27','shahrestan'=>'نکا',],
            ['id'=>'396','ostan_id'=>'27','shahrestan'=>'نور',],
            ['id'=>'397','ostan_id'=>'27','shahrestan'=>'نوشهر',],
            ['id'=>'398','ostan_id'=>'27','shahrestan'=>'فریدونکنار',],
            ['id'=>'399','ostan_id'=>'28','shahrestan'=>'آشتیان',],
            ['id'=>'400','ostan_id'=>'28','shahrestan'=>'اراک',],
            ['id'=>'401','ostan_id'=>'28','shahrestan'=>'تفرش',],
            ['id'=>'402','ostan_id'=>'28','shahrestan'=>'خمین',],
            ['id'=>'403','ostan_id'=>'28','shahrestan'=>'دلیجان',],
            ['id'=>'404','ostan_id'=>'28','shahrestan'=>'زرندیه',],
            ['id'=>'405','ostan_id'=>'28','shahrestan'=>'ساوه',],
            ['id'=>'406','ostan_id'=>'28','shahrestan'=>'شازند',],
            ['id'=>'407','ostan_id'=>'28','shahrestan'=>'کمیجان',],
            ['id'=>'408','ostan_id'=>'28','shahrestan'=>'محلات',],
            ['id'=>'409','ostan_id'=>'29','shahrestan'=>'بندرعباس',],
            ['id'=>'410','ostan_id'=>'29','shahrestan'=>'میناب',],
            ['id'=>'411','ostan_id'=>'29','shahrestan'=>'بندر لنگه',],
            ['id'=>'412','ostan_id'=>'29','shahrestan'=>'رودان-دهبارز',],
            ['id'=>'413','ostan_id'=>'29','shahrestan'=>'جاسک',],
            ['id'=>'414','ostan_id'=>'29','shahrestan'=>'قشم',],
            ['id'=>'415','ostan_id'=>'29','shahrestan'=>'حاجی آباد',],
            ['id'=>'416','ostan_id'=>'29','shahrestan'=>'ابوموسی',],
            ['id'=>'417','ostan_id'=>'29','shahrestan'=>'بستک',],
            ['id'=>'418','ostan_id'=>'29','shahrestan'=>'گاوبندی',],
            ['id'=>'419','ostan_id'=>'29','shahrestan'=>'خمیر',],
            ['id'=>'420','ostan_id'=>'30','shahrestan'=>'اسدآباد',],
            ['id'=>'421','ostan_id'=>'30','shahrestan'=>'بهار',],
            ['id'=>'422','ostan_id'=>'30','shahrestan'=>'تویسرکان',],
            ['id'=>'423','ostan_id'=>'30','shahrestan'=>'رزن',],
            ['id'=>'424','ostan_id'=>'30','shahrestan'=>'کبودر آهنگ',],
            ['id'=>'425','ostan_id'=>'30','shahrestan'=>'ملایر',],
            ['id'=>'426','ostan_id'=>'30','shahrestan'=>'نهاوند',],
            ['id'=>'427','ostan_id'=>'30','shahrestan'=>'همدان',],
            ['id'=>'428','ostan_id'=>'31','shahrestan'=>'ابرکوه',],
            ['id'=>'429','ostan_id'=>'31','shahrestan'=>'اردکان',],
            ['id'=>'430','ostan_id'=>'31','shahrestan'=>'بافق',],
            ['id'=>'431','ostan_id'=>'31','shahrestan'=>'تفت',],
            ['id'=>'432','ostan_id'=>'31','shahrestan'=>'خاتم',],
            ['id'=>'433','ostan_id'=>'31','shahrestan'=>'صدوق',],
            ['id'=>'434','ostan_id'=>'31','shahrestan'=>'طبس',],
            ['id'=>'435','ostan_id'=>'31','shahrestan'=>'مهریز',],
            ['id'=>'436','ostan_id'=>'31','shahrestan'=>'میبد',],
            ['id'=>'437','ostan_id'=>'31','shahrestan'=>'یزد',],
            ['id'=>'438','ostan_id'=>'8','shahrestan'=>'قرچک',],
            ['id'=>'439','ostan_id'=>'8','shahrestan'=>'گلستان',],
            ['id'=>'440','ostan_id'=>'8','shahrestan'=>'قدس',],
            ['id'=>'441','ostan_id'=>'8','shahrestan'=>'ملارد',],
            ['id'=>'442','ostan_id'=>'8','shahrestan'=>'نسیم‌شهر',],
            ['id'=>'443','ostan_id'=>'8','shahrestan'=>'اندیشه',],
            ['id'=>'444','ostan_id'=>'8','shahrestan'=>'صالح‌آباد',],
            ['id'=>'445','ostan_id'=>'8','shahrestan'=>'باقرشهر',],
            ['id'=>'446','ostan_id'=>'8','shahrestan'=>'باغستان',],
            ['id'=>'447','ostan_id'=>'8','shahrestan'=>'بومهن',],
            ['id'=>'448','ostan_id'=>'8','shahrestan'=>'چهاردانگه',],
            ['id'=>'449','ostan_id'=>'8','shahrestan'=>'پیشوا',],
            ['id'=>'450','ostan_id'=>'8','shahrestan'=>'پردیس',],
            ['id'=>'451','ostan_id'=>'8','shahrestan'=>'وحیدیه',],
            ['id'=>'452','ostan_id'=>'8','shahrestan'=>'نصیرآباد',],
            ['id'=>'453','ostan_id'=>'8','shahrestan'=>'فردوسیه',],
            ['id'=>'454','ostan_id'=>'8','shahrestan'=>'حسن‌آباد',],
            ['id'=>'455','ostan_id'=>'8','shahrestan'=>'رودهن',],
            ['id'=>'456','ostan_id'=>'8','shahrestan'=>'شاهدشهر',],
            ['id'=>'457','ostan_id'=>'8','shahrestan'=>'صباشهر',],
            ['id'=>'458','ostan_id'=>'8','shahrestan'=>'صفادشت',],
            ['id'=>'459','ostan_id'=>'8','shahrestan'=>'لواسان',],
            ['id'=>'460','ostan_id'=>'8','shahrestan'=>'آبسرد',],
            ['id'=>'461','ostan_id'=>'8','shahrestan'=>'شریف‌آباد',],
            ['id'=>'462','ostan_id'=>'8','shahrestan'=>'کهریزک',],
            ['id'=>'463','ostan_id'=>'8','shahrestan'=>'فشم'],
            ['id'=>'464','ostan_id'=>'8','shahrestan'=>'جوادآباد',],
            ['id'=>'465','ostan_id'=>'8','shahrestan'=>'کیلان'],
            ['id'=>'466','ostan_id'=>'8','shahrestan'=>'آبعلی'],
            ['id'=>'467','ostan_id'=>'8','shahrestan'=>'ارجمند'],
            ['id'=>'468','ostan_id'=>'29','shahrestan'=>'کیش'],
            ['id'=>'469','ostan_id'=>'29','shahrestan'=>'لاوان'],
            ['id'=>'470','ostan_id'=>'29','shahrestan'=>'پارسیان'],
            ['id'=>'471','ostan_id'=>'29','shahrestan'=>'سیریک'],
            ['id'=>'472','ostan_id'=>'29','shahrestan'=>'بشاگرد'],

            ]);

        }
    }